GET http://localhost:5039

###
GET http://localhost:5039/employees

###
GET http://localhost:5039/employees/311122334455566

###
GET http://localhost:5039/employees/find?nik=1234&name=john

###
POST http://localhost:5039/employees
Content-Type: application/json

{
    "NIK": "311122334455566",
    "Name": "Bagus Hendrawan",
    "Gender": "Male",
    "Birth": "2002-06-07",
    "Address": "Jakarta Timur",
    "Country": "Indonesia"
}

###
PUT http://localhost:5039/employees/3177766165432114
Content-Type: application/json

{
    "Name": "Johnny Doe Updated",
    "Gender": "Male",
    "Birth": "2002-06-12",
    "Address": "Jakarta Utara",
    "Country": "Indonesia"
}

###
DELETE http://localhost:5039/employees/311122334455566